// Generated by diesel_ext

#![allow(unused)]
#![allow(clippy::all)]

use chrono::NaiveDateTime;

#[derive(Queryable, Debug)]
pub struct AdminRole {
    pub created_at: Option<NaiveDateTime>,
    pub updated_at: Option<NaiveDateTime>,
    pub deleted_at: Option<NaiveDateTime>,
    pub id: usize,
    pub user_name: Option<String>,
    pub password: Option<String>,
    pub role: Option<String>,
}

#[derive(Queryable, Debug)]
pub struct Asset {
    pub created_at: Option<NaiveDateTime>,
    pub updated_at: Option<NaiveDateTime>,
    pub deleted_at: Option<NaiveDateTime>,
    pub id: usize,
    pub user_id: usize,
    pub type_: Option<isize>,
    pub available_asset: Option<String>,
    pub total_asset: Option<String>,
}

#[derive(Queryable, Debug)]
pub struct BehaviorDetail {
    pub created_at: Option<NaiveDateTime>,
    pub updated_at: Option<NaiveDateTime>,
    pub deleted_at: Option<NaiveDateTime>,
    pub id: usize,
    pub user_id: Option<usize>,
    pub type_: Option<isize>,
    pub a_factor: Option<usize>,
    pub h_factor: Option<usize>,
    pub factor: Option<isize>,
    pub state: Option<isize>,
}

#[derive(Queryable, Debug)]
pub struct NtTxDetail {
    pub created_at: Option<NaiveDateTime>,
    pub updated_at: Option<NaiveDateTime>,
    pub deleted_at: Option<NaiveDateTime>,
    pub id: usize,
    pub user_id: usize,
    pub amount: Option<String>,
    pub tx_type: Option<isize>,
    pub tx_state: Option<isize>,
    pub comment: Option<String>,
    pub object_id: Option<usize>,
}

#[derive(Queryable, Debug)]
pub struct NtUserStashe {
    pub created_at: Option<NaiveDateTime>,
    pub updated_at: Option<NaiveDateTime>,
    pub deleted_at: Option<NaiveDateTime>,
    pub id: usize,
    pub user_name: Option<String>,
    pub password: Option<String>,
    pub name: Option<String>,
    pub mobile: Option<String>,
    pub id_card: String,
    pub user_type: Option<isize>,
    pub node_type: Option<isize>,
    pub is_ok: Option<bool>,
}

#[derive(Queryable, Debug)]
pub struct NtUser {
    pub created_at: Option<NaiveDateTime>,
    pub updated_at: Option<NaiveDateTime>,
    pub deleted_at: Option<NaiveDateTime>,
    pub id: usize,
    pub user_name: Option<String>,
    pub password: Option<String>,
    pub name: Option<String>,
    pub mobile: Option<String>,
    pub id_card: String,
    pub user_type: Option<isize>,
    pub node_type: Option<isize>,
    pub is_ok: Option<bool>,
}

#[derive(Queryable, Debug)]
pub struct PayType {
    pub created_at: Option<NaiveDateTime>,
    pub updated_at: Option<NaiveDateTime>,
    pub deleted_at: Option<NaiveDateTime>,
    pub type_: Option<isize>,
    pub uint: Option<isize>,
    pub gos: Option<String>,
    pub rmb: Option<String>,
}

#[derive(Queryable, Debug)]
pub struct RechargeRecord {
    pub created_at: Option<NaiveDateTime>,
    pub updated_at: Option<NaiveDateTime>,
    pub deleted_at: Option<NaiveDateTime>,
    pub id: usize,
    pub user_id: Option<usize>,
    pub amount: Option<String>,
    pub order_id: Option<String>,
    pub order_type: Option<isize>,
    pub state: Option<isize>,
    pub comment: Option<String>,
}

#[derive(Queryable, Debug)]
pub struct SpaceTxe {
    pub created_at: Option<NaiveDateTime>,
    pub updated_at: Option<NaiveDateTime>,
    pub deleted_at: Option<NaiveDateTime>,
    pub id: usize,
    pub user_id: usize,
    pub tx_state: Option<isize>,
    pub space_amount: Option<String>,
    pub expired_at: Option<NaiveDateTime>,
    pub tx_type: Option<isize>,
    pub object_id: Option<usize>,
}

#[derive(Queryable, Debug)]
pub struct SpeedType {
    pub created_at: Option<NaiveDateTime>,
    pub updated_at: Option<NaiveDateTime>,
    pub deleted_at: Option<NaiveDateTime>,
    pub user_id: usize,
    pub speed_type: Option<isize>,
    pub first_login: Option<bool>,
}

#[derive(Queryable, Debug)]
pub struct Task {
    pub created_at: Option<NaiveDateTime>,
    pub updated_at: Option<NaiveDateTime>,
    pub deleted_at: Option<NaiveDateTime>,
    pub id: usize,
    pub task_name: Option<String>,
    pub star_time: Option<usize>,
    pub end_time: Option<usize>,
    pub start_time: Option<NaiveDateTime>,
}

#[derive(Queryable, Debug)]
pub struct Top {
    pub created_at: Option<NaiveDateTime>,
    pub updated_at: Option<NaiveDateTime>,
    pub deleted_at: Option<NaiveDateTime>,
    pub user_id: usize,
    pub top0: Option<usize>,
    pub top1: Option<usize>,
    pub top2: Option<usize>,
    pub top3: Option<usize>,
}

#[derive(Queryable, Debug)]
pub struct UserRelation {
    pub created_at: Option<NaiveDateTime>,
    pub updated_at: Option<NaiveDateTime>,
    pub deleted_at: Option<NaiveDateTime>,
    pub id: usize,
    pub user_id: usize,
    pub type_: Option<isize>,
    pub object_id: usize,
}
